apiVersion: apps/v1
kind: Deployment
metadata:
  name: swine-frontend
  labels:
    app: swine-frontend
spec:
  selector:
    matchLabels:
      app: swine-frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: swine-frontend
    spec:
      containers:
        - name: swine-frontend-nginx
          image: registry.digitalocean.com/swine-registry/swine-frontend:${TAG}
          ports:
            - containerPort: 80
              name: http-frontend
